name: Pipeline Local com Vagrant

on:
  push:
    branches:
      - 'master'

jobs:
  setup-build-publis-deploy-local:
    runs-on: self-hosted
    environment: master
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Compilando imagem Docker
        run: docker build -t 192.168.100.128:5000/aplicacao-pipeline-local:${{ github.sha }} .

      - name: Enviando imagem Docker
        run: docker push 192.168.100.128:5000/aplicacao-pipeline-local:${{ github.sha }}

      - name: Configurando arquivo deployment
        run: |
          yq eval '.spec.template.spec.containers[0].image = "'aplicacao-pipeline-local:${{ github.sha }}'"' deployment.yml | cat > new.yml && mv new.yml deployment.yml
          cat deployment.yml

#      - name: Atualizando cluster
 #       run:  kubectl apply -f deployment.yml